export const qdata = [
  [1, "Al-Fatihah", "The Opener", "الفاتحة"],
  [2, "Al-Baqarah", "The Cow", "البقرة"],
  [3, "Ali 'Imran", "Family of Imran", "آل عمران"],
  [4, "An-Nisa", "The Women", "النساء"],
  [5, "Al-Ma'idah", "The Table Spread", "المائدة"],
  [6, "Al-An'am", "The Cattle", "الأنعام"],
  [7, "Al-A'raf", "The Heights", "الأعراف"],
  [8, "Al-Anfal", "The Spoils of War", "الأنفال"],
  [9, "At-Tawbah", "The Repentance", "التوبة"],
  [10, "Yunus", "Jonah", "يونس"],
  [11, "Hud", "Hud", "هود"],
  [12, "Yusuf", "Joseph", "يوسف"],
  [13, "Ar-Ra'd", "The Thunder", "الرعد"],
  [14, "Ibrahim", "Abraham", "ابراهيم"],
  [15, "Al-Hijr", "The Rocky Tract", "الحجر"],
  [16, "An-Nahl", "The Bee", "النحل"],
  [17, "Al-Isra", "The Night Journey", "الإسراء"],
  [18, "Al-Kahf", "The Cave", "الكهف"],
  [19, "Maryam", "Mary", "مريم"],
  [20, "Taha", "Ta-Ha", "طه"],
  [21, "Al-Anbya", "The Prophets", "الأنبياء"],
  [22, "Al-Hajj", "The Pilgrimage", "الحج"],
  [23, "Al-Mu'minun", "The Believers", "المؤمنون"],
  [24, "An-Nur", "The Light", "النور"],
  [25, "Al-Furqan", "The Criterion", "الفرقان"],
  [26, "Ash-Shu'ara", "The Poets", "الشعراء"],
  [27, "An-Naml", "The Ant", "النمل"],
  [28, "Al-Qasas", "The Stories", "القصص"],
  [29, "Al-'Ankabut", "The Spider", "العنكبوت"],
  [30, "Ar-Rum", "The Romans", "الروم"],
  [31, "Luqman", "Luqman", "لقمان"],
  [32, "As-Sajdah", "The Prostration", "السجدة"],
  [33, "Al-Ahzab", "The Combined Forces", "الأحزاب"],
  [34, "Saba", "Sheba", "سبإ"],
  [35, "Fatir", "Originator", "فاطر"],
  [36, "Ya-Sin", "Ya Sin", "يس"],
  [37, "As-Saffat", "Those who set the Ranks", "الصافات"],
  [38, "Sad", 'The Letter "Saad"', "ص"],
  [39, "Az-Zumar", "The Troops", "الزمر"],
  [40, "Ghafir", "The Forgiver", "غافر"],
  [41, "Fussilat", "Explained in Detail", "فصلت"],
  [42, "Ash-Shuraa", "The Consultation", "الشورى"],
  [43, "Az-Zukhruf", "The Ornaments of Gold", "الزخرف"],
  [44, "Ad-Dukhan", "The Smoke", "الدخان"],
  [45, "Al-Jathiyah", "The Crouching", "الجاثية"],
  [46, "Al-Ahqaf", "The Wind-Curved Sandhills", "الأحقاف"],
  [47, "Muhammad", "Muhammad", "محمد"],
  [48, "Al-Fath", "The Victory", "الفتح"],
  [49, "Al-Hujurat", "The Rooms", "الحجرات"],
  [50, "Qaf", 'The Letter "Qaf"', "ق"],
  [51, "Adh-Dhariyat", "The Winnowing Winds", "الذاريات"],
  [52, "At-Tur", "The Mount", "الطور"],
  [53, "An-Najm", "The Star", "النجم"],
  [54, "Al-Qamar", "The Moon", "القمر"],
  [55, "Ar-Rahman", "The Beneficent", "الرحمن"],
  [56, "Al-Waqi'ah", "The Inevitable", "الواقعة"],
  [57, "Al-Hadid", "The Iron", "الحديد"],
  [58, "Al-Mujadila", "The Pleading Woman", "المجادلة"],
  [59, "Al-Hashr", "The Exile", "الحشر"],
  [60, "Al-Mumtahanah", "She that is to be examined", "الممتحنة"],
  [61, "As-Saf", "The Ranks", "الصف"],
  [62, "Al-Jumu'ah", "The Congregation, Friday", "الجمعة"],
  [63, "Al-Munafiqun", "The Hypocrites", "المنافقون"],
  [64, "At-Taghabun", "The Mutual Disillusion", "التغابن"],
  [65, "At-Talaq", "The Divorce", "الطلاق"],
  [66, "At-Tahrim", "The Prohibition", "التحريم"],
  [67, "Al-Mulk", "The Sovereignty", "الملك"],
  [68, "Al-Qalam", "The Pen", "القلم"],
  [69, "Al-Haqqah", "The Reality", "الحاقة"],
  [70, "Al-Ma'arij", "The Ascending Stairways", "المعارج"],
  [71, "Nuh", "Noah", "نوح"],
  [72, "Al-Jinn", "The Jinn", "الجن"],
  [73, "Al-Muzzammil", "The Enshrouded One", "المزمل"],
  [74, "Al-Muddaththir", "The Cloaked One", "المدثر"],
  [75, "Al-Qiyamah", "The Resurrection", "القيامة"],
  [76, "Al-Insan", "The Man", "الانسان"],
  [77, "Al-Mursalat", "The Emissaries", "المرسلات"],
  [78, "An-Naba", "The Tidings", "النبإ"],
  [79, "An-Nazi'at", "Those who drag forth", "النازعات"],
  [80, "'Abasa", "He Frowned", "عبس"],
  [81, "At-Takwir", "The Overthrowing", "التكوير"],
  [82, "Al-Infitar", "The Cleaving", "الإنفطار"],
  [83, "Al-Mutaffifin", "The Defrauding", "المطففين"],
  [84, "Al-Inshiqaq", "The Sundering", "الإنشقاق"],
  [85, "Al-Buruj", "The Mansions of the Stars", "البروج"],
  [86, "At-Tariq", "The Nightcommer", "الطارق"],
  [87, "Al-A'la", "The Most High", "الأعلى"],
  [88, "Al-Ghashiyah", "The Overwhelming", "الغاشية"],
  [89, "Al-Fajr", "The Dawn", "الفجر"],
  [90, "Al-Balad", "The City", "البلد"],
  [91, "Ash-Shams", "The Sun", "الشمس"],
  [92, "Al-Layl", "The Night", "الليل"],
  [93, "Ad-Duhaa", "The Morning Hours", "الضحى"],
  [94, "Ash-Sharh", "The Relief", "الشرح"],
  [95, "At-Tin", "The Fig", "التين"],
  [96, "Al-'Alaq", "The Clot", "العلق"],
  [97, "Al-Qadr", "The Power", "القدر"],
  [98, "Al-Bayyinah", "The Clear Proof", "البينة"],
  [99, "Az-Zalzalah", "The Earthquake", "الزلزلة"],
  [100, "Al-'Adiyat", "The Courser", "العاديات"],
  [101, "Al-Qari'ah", "The Calamity", "القارعة"],
  [102, "At-Takathur", "The Rivalry in world increase", "التكاثر"],
  [103, "Al-'Asr", "The Declining Day", "العصر"],
  [104, "Al-Humazah", "The Traducer", "الهمزة"],
  [105, "Al-Fil", "The Elephant", "الفيل"],
  [106, "Quraysh", "Quraysh", "قريش"],
  [107, "Al-Ma'un", "The Small kindnesses", "الماعون"],
  [108, "Al-Kawthar", "The Abundance", "الكوثر"],
  [109, "Al-Kafirun", "The Disbelievers", "الكافرون"],
  [110, "An-Nasr", "The Divine Support", "النصر"],
  [111, "Al-Masad", "The Palm Fiber", "المسد"],
  [112, "Al-Ikhlas", "The Sincerity", "الإخلاص"],
  [113, "Al-Falaq", "The Daybreak", "الفلق"],
  [114, "An-Nas", "Mankind", "الناس"],
];
